### ISSUE TITLE
Failed to load application: No module named 'bcrypt'

### ISSUE THREAD

**Issue by MisterButcher** [lanjelot/twisted-honeypots#6]
Hello, 
i am trying to make this work, but startup fails with error bcrypt missing, although it is aviakable.

root@ubuntu:/opt/twisted-honeypots# ./start.sh
Unhandled Error
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/twisted/application/app.py", line 678, in run
    runApp(config)
  File "/root/.local/lib/python3.6/site-packages/twisted/scripts/twistd.py", line 30, in runApp
    runner.run()
  File "/root/.local/lib/python3.6/site-packages/twisted/application/app.py", line 372, in run
    self.application = self.createOrGetApplication()
  File "/root/.local/lib/python3.6/site-packages/twisted/application/app.py", line 439, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/root/.local/lib/python3.6/site-packages/twisted/application/app.py", line 448, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/root/.local/lib/python3.6/site-packages/twisted/application/service.py", line 404, in loadApplication
    application = sob.loadValueFromFile(filename, "application")
  File "/root/.local/lib/python3.6/site-packages/twisted/persisted/sob.py", line 176, in loadValueFromFile
    eval(codeObj, d, d)
  File "/opt/twisted-honeypots/python/start-all-pot.tac", line 3, in <module>
    from sshpot import PotSSHFactory
  File "/opt/twisted-honeypots/python/sshpot.py", line 7, in <module>
    from twisted.conch.ssh import factory, keys, transport, userauth, connection
  File "/root/.local/lib/python3.6/site-packages/twisted/conch/ssh/factory.py", line 17, in <module>
    from twisted.conch.ssh import _kex, transport, userauth, connection
  File "/root/.local/lib/python3.6/site-packages/twisted/conch/ssh/transport.py", line 36, in <module>
    from twisted.conch.ssh import address, keys, _kex
  File "/root/.local/lib/python3.6/site-packages/twisted/conch/ssh/keys.py", line 18, in <module>
    import bcrypt
builtins.ModuleNotFoundError: No module named 'bcrypt'

Failed to load application: No module named 'bcrypt'

root@ubuntu:/opt/twisted-honeypots# bcrypt
Usage is: bcrypt -[orc][-sN] file1 file2..
  -o Write output to standard out
  -r Do NOT remove input files after processing
  -c Do NOT compress files before encryption
  -sN How many times to overwrite input files with random data
root@ubuntu:/opt/twisted-honeypots#

Any Idea?

**Comment by MisterButcher** [comment]
i had to install it again in python 3 environment. after that, i was missed some other installations, and then finally it worked. 
sorry for opening an issue

**Comment by gh0st-anonymous** [comment]
> Hello, i am trying to make this work, but startup fails with error bcrypt missing, although it is aviakable.
> 
> root@ubuntu:/opt/twisted-honeypots# ./start.sh Unhandled Error Traceback (most recent call last): File "/root/.local/lib/python3.6/site-packages/twisted/application/app.py", line 678, in run runApp(config) File "/root/.local/lib/python3.6/site-packages/twisted/scripts/twistd.py", line 30, in runApp runner.run() File "/root/.local/lib/python3.6/site-packages/twisted/application/app.py", line 372, in run self.application = self.createOrGetApplication() File "/root/.local/lib/python3.6/site-packages/twisted/application/app.py", line 439, in createOrGetApplication application = getApplication(self.config, passphrase) --- --- File "/root/.local/lib/python3.6/site-packages/twisted/application/app.py", line 448, in getApplication application = service.loadApplication(filename, style, passphrase) File "/root/.local/lib/python3.6/site-packages/twisted/application/service.py", line 404, in loadApplication application = sob.loadValueFromFile(filename, "application") File "/root/.local/lib/python3.6/site-packages/twisted/persisted/sob.py", line 176, in loadValueFromFile eval(codeObj, d, d) File "/opt/twisted-honeypots/python/start-all-pot.tac", line 3, in from sshpot import PotSSHFactory File "/opt/twisted-honeypots/python/sshpot.py", line 7, in from twisted.conch.ssh import factory, keys, transport, userauth, connection File "/root/.local/lib/python3.6/site-packages/twisted/conch/ssh/factory.py", line 17, in from twisted.conch.ssh import _kex, transport, userauth, connection File "/root/.local/lib/python3.6/site-packages/twisted/conch/ssh/transport.py", line 36, in from twisted.conch.ssh import address, keys, _kex File "/root/.local/lib/python3.6/site-packages/twisted/conch/ssh/keys.py", line 18, in import bcrypt builtins.ModuleNotFoundError: No module named 'bcrypt'
> 
> Failed to load application: No module named 'bcrypt'
> 
> root@ubuntu:/opt/twisted-honeypots# bcrypt Usage is: bcrypt -[orc][-sN] file1 file2.. -o Write output to standard out -r Do NOT remove input files after processing -c Do NOT compress files before encryption -sN How many times to overwrite input files with random data root@ubuntu:/opt/twisted-honeypots#
> 
> Any Idea?

hi, could you help me about the other installations and dependencies pls ? i have no idea how to setup the script.

**Comment by Gh0stAn0n** [comment]
> i had to install it again in python 3 environment. after that, i was missed some other installations, and then finally it worked. sorry for opening an issue

hi, could you help me about the other installations and dependencies pls ? i have no idea how to setup the script.
